# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    stepone_service:
        class: AppBundle\Service\StepOne

    steptwo_service:
        class: AppBundle\Service\StepTwo

    stepthree_service:
        class: AppBundle\Service\StepThree
